<?php

declare(strict_types=1);

namespace Plugins\Auth\Infrastructure\Http\Stages;

use AlfacodeTeam\PhpServicePlatform\Kernel\Events\EventBus;
use AlfacodeTeam\PhpServicePlatform\Kernel\Http\Request;
use AlfacodeTeam\PhpServicePlatform\Kernel\Http\Response;
use AlfacodeTeam\PhpServicePlatform\Kernel\Pipelines\Http\Contracts\HttpStageContract;
use AlfacodeTeam\PhpServicePlatform\Kernel\Ports\SessionPort;
use Plugins\Auth\API\IntegrationEvents\AuthSessionIntegrationEvent;
use Plugins\Session\Infrastructure\Http\StartSessionStage;

/**
 * The `fresh-session` route filter — a sign-in or sign-up page starts clean.
 *
 *     { "method": "GET", "path": "/login", "handler": "…", "filters": ["fresh-session"] }
 *
 * A session that expired, or a browser someone else signed out of, still
 * carries whatever other plugins parked in it: a remembered organisation, a
 * half-finished flow. The guard's login() rotates the session id but KEEPS those
 * attributes, so they would follow the next person to sign in. On a sign-in page
 * that is never wanted.
 *
 * For a SIGNED-OUT visitor on a GET, this filter:
 *
 *   1. replaces the session with a new one (new id, attributes dropped), keeping
 *      only what the page itself needs — the "return to" URL the login redirect
 *      reads, and flash messages ("your password was reset, sign in");
 *   2. dispatches `auth.session.reset`, so a plugin holding state OUTSIDE the
 *      session — a cookie — clears it too. Tenancy forgets the active
 *      organisation this way; Auth does not know that cookie exists.
 *
 * A signed-in visitor is left alone: wiping their session from a page view would
 * sign them out, and a page that should not be shown to them redirects instead.
 * A remember-me visitor counts as signed in — SessionAuthStage (22) resurrects
 * them before route filters run. Non-GET requests are left alone so the filter
 * can never destroy the session a form is posting into.
 *
 * An EMPTY session is not replaced: minting a new one would send every bot that
 * fetches /login a session cookie it never needed.
 */
final class FreshSessionStage implements HttpStageContract
{
    public const string ALIAS = 'fresh-session';

    public function handle(Request $request, callable $next): Response
    {
        if (!\in_array($request->method(), ['GET', 'HEAD'], true)) {
            return $next($request);
        }

        $identity = $request->identity();
        if ($identity !== null && !$identity->isGuest()) {
            return $next($request);
        }

        $container = $request->container();
        if ($container === null) {
            return $next($request);
        }

        if ($container->has(SessionPort::class)) {
            $session = $container->make(SessionPort::class);
            if ($session instanceof SessionPort) {
                self::renew($session);
            }
        }

        if ($container->has(EventBus::class)) {
            $container->make(EventBus::class)->dispatch(
                new AuthSessionIntegrationEvent(AuthSessionIntegrationEvent::RESET),
            );
        }

        return $next($request);
    }

    /** Replace the session, carrying over only what a sign-in page reads. */
    public static function renew(SessionPort $session): void
    {
        $all = $session->all();

        $flashed = array_merge(
            is_array($all['_flash.new'] ?? null) ? $all['_flash.new'] : [],
            is_array($all['_flash.old'] ?? null) ? $all['_flash.old'] : [],
        );

        $keep = [];
        foreach ([StartSessionStage::PREVIOUS_URL, '_flash.new', '_flash.old', ...$flashed] as $key) {
            if (is_string($key) && array_key_exists($key, $all)) {
                $keep[$key] = $all[$key];
            }
        }

        // The CSRF token is regenerated by invalidate() anyway; it is not state
        // worth a new session on its own.
        if (array_diff_key($all, $keep, ['_token' => true]) === []) {
            return;
        }

        $session->invalidate();

        foreach ($keep as $key => $value) {
            $session->put($key, $value);
        }
    }
}
